In [27]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
from tensorflow.python.client import device_lib

print('tensorflow version',tf.__version__)

x = [[3.]]
y = [[4.]]
print('Result:{}'.format(tf.matmul(x,y)))

tensorflow version 2.3.1
Result:[[12.]]


In [28]:
print(device_lib.list_local_devices())

[name: &quot;/device:CPU:0&quot;
device_type: &quot;CPU&quot;
memory_limit: 268435456
locality {
}
incarnation: 11429817421096618177
, name: &quot;/device:XLA_CPU:0&quot;
device_type: &quot;XLA_CPU&quot;
memory_limit: 17179869184
locality {
}
incarnation: 1178496050685700997
physical_device_desc: &quot;device: XLA_CPU device&quot;
, name: &quot;/device:XLA_GPU:0&quot;
device_type: &quot;XLA_GPU&quot;
memory_limit: 17179869184
locality {
}
incarnation: 4761158332721499567
physical_device_desc: &quot;device: XLA_GPU device&quot;
]


In [29]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [30]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [31]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-1.4316803e-01, -6.2647700e-01, -4.0834403e-01, -7.3497611e-01,
         2.0402095e-01,  1.0499082e+00,  3.2707125e-01,  9.2745572e-04,
        -7.3698175e-01,  1.1405690e-01]], dtype=float32)

In [32]:
tf.nn.softmax(predictions).numpy()

array([[0.0816303 , 0.05034461, 0.06261623, 0.04516816, 0.11551374,
        0.2691521 , 0.13063926, 0.09428254, 0.04507766, 0.10557541]],
      dtype=float32)

In [33]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [34]:
loss_fn(y_train[:1], predictions).numpy()

1.3124785

In [35]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [36]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 497us/step - loss: 0.2985 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 1s 489us/step - loss: 0.1416 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 1s 502us/step - loss: 0.1075 - accuracy: 0.9682
Epoch 4/5
1875/1875 [==============================] - 1s 492us/step - loss: 0.0885 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 1s 490us/step - loss: 0.0762 - accuracy: 0.9760


&lt;tensorflow.python.keras.callbacks.History at 0x28e951a0630&gt;

In [37]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0804 - accuracy: 0.9742


[0.08038263767957687, 0.9742000102996826]

In [38]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [39]:
probability_model(x_test[:5])


&lt;tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.40109905e-08, 6.60775754e-08, 4.22205517e-07, 3.08718736e-05,
        1.31356170e-09, 2.38703493e-08, 7.89902269e-13, 9.99965549e-01,
        5.16754888e-08, 3.05845560e-06],
       [3.91180999e-09, 1.16960968e-04, 9.99880433e-01, 2.52384280e-06,
        3.75332411e-15, 1.12024694e-07, 4.54909665e-09, 2.10496963e-12,
        1.33838824e-08, 7.44708860e-14],
       [3.26648632e-07, 9.99599278e-01, 1.81972588e-04, 1.17589525e-06,
        7.90936156e-06, 1.37180757e-06, 3.18614025e-06, 1.98198482e-04,
        6.15604085e-06, 3.23700732e-07],
       [9.99964595e-01, 6.42930971e-08, 1.62141841e-05, 7.16204795e-07,
        1.07679703e-07, 6.24815129e-06, 1.98611383e-06, 9.22563049e-06,
        4.93391532e-08, 8.06191906e-07],
       [2.30204023e-06, 2.37927122e-09, 1.22889219e-06, 8.95977248e-09,
        9.94749963e-01, 5.83669475e-07, 5.23239078e-06, 3.47223831e-05,
        1.13924315e-07, 5.20582497e-03]], dtype=float32)&gt;